### ISSUE TITLE
hello world from readme not working

### ISSUE THREAD

**Issue by gurugeek** [DronRathore/goexpress#28]
I just tried the hello world from the readme and go throws this error

```
# command-line-arguments
./main.go:8:16: cannot use func literal (type func(*goexpress.Request, *goexpress.Response)) as type goexpress.Middleware in argument to app.Get
./main.go:9:8: res.Write undefined (type *goexpress.Response is pointer to interface, not interface)
```

**Comment by DronRathore** [comment]
Aah my bad, those are turned into interfaces so you will have to remove “*” from the variables. Thanks for pointing out, will update the Readme, also it seems I am not receiving any email notification for issues on this repo, sorry for delayed response.

**Comment by DronRathore** [comment]
Also you can take a look at examples folder for sample code. Let me know if I should add more examples in there.
