### ISSUE TITLE
Why can't turn off logging every request?

### ISSUE THREAD

**Issue by icebob** [DronRathore/goexpress#5]
In [Line #61](https://github.com/DronRathore/goexpress/blob/master/request/request.go#L61) you log out every request  to console. It would be better to use a logging middleware like [morgan](https://github.com/expressjs/morgan) in ExpressJS. What do you think?

**Comment by DronRathore** [comment]
Good point. Done. 😄

**Comment by icebob** [comment]
Thanks!
